lst = [1, 2, 3]
print(lst)                  # i) list()
print(len(lst))            # ii) len()
print(lst.count(2))        # iii) count()
print(lst.index(3))        # iv) index()
lst.append(4)              # v) append()
lst.insert(1, 10)          # vi) insert()
lst.extend([5, 6])         # vii) extend()
lst.remove(2)              # viii) remove()
lst.pop()                  # ix) pop()
lst.reverse()              # x) reverse()
lst.sort()                 # xi) sort()
copy_lst = lst.copy()      # xii) copy()
lst.clear()                # xiii) clear()
